use_frameworks!
use_modular_headers!
platform :ios, '10.0'
source 'https://cdn.cocoapods.org/'

target 'AccessibilitySnapshotDemo' do
	pod 'Paralayout', '~> 0.9'

	target 'SnapshotTests' do
		inherit! :search_paths

		pod 'AccessibilitySnapshot/Core'
		pod 'AccessibilitySnapshot+SnapshotTesting', :path => '../AccessibilitySnapshot+SnapshotTesting.podspec'
	end
end

project 'AccessibilitySnapshot.xcodeproj'

install! 'cocoapods', :disable_input_output_paths => true
